joy_teleop:
  ros__parameters:
    piloting:
      type: topic
      interface_type: geometry_msgs/msg/Twist
      topic_name: cmd_vel
      deadman_buttons: [5]  # R shoulder button
      axis_mappings:
        linear-x:
          axis: 1  # D-Pad vertical axis
          scale: 0.4
          offset: 0.0
        angular-z:
          axis: 0  # D-Pad horizontal axis
          scale: 2.5
          offset: 0.0

    dock:
      type: topic
      interface_type: std_msgs/msg/Empty
      topic_name: dock
      deadman_buttons: [3]  # X button
      message_value: {}
