teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.3
    scale_linear_turbo:
      x: 1.5

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.7
    scale_angular_turbo:
      yaw: 3.0

    enable_button: 5  # R shoulder button
    enable_turbo_button: 4  # L shoulder button
